theme = "base16_terminal"

[editor]
line-number = "absolute"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false


[editor.whitespace.render]
tab = "all"
nbsp = "all"
# newline = "none"
# space = "all"

[editor.whitespace.characters]
nbsp = "⍽"
tab = "→"
# newline = "⏎"
# tabpad = "·" # Tabs will look like "→···" (depending on tab width)
# space = "·"

# [editor.indent-guides]
# render = true