[language-server.godot]
command = "nc" 
args = [ "127.0.0.1", "6005"]

[[language]]
name = "gdscript"
language-servers = ["godot"] 

# npm i -g @astrojs/language-server
[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = { "typescript" = { "tsdk" = "/home/kris/.nvm/versions/node/v20.11.0/lib/node_modules/typescript/lib/"}, "environment" = "node" }

[[language]]
name = "astro"
auto-format = true
language-servers = [ "astro-ls" ]
